# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               JDS
tagline:             'Research fellow in numerical analysis'
description:         ''
url:                 http://jonathan-d-shaw.github.io
baseurl:             ''
plugins: 
    - jekyll-paginate
    - jekyll-seo-tag
paginate:            5
paginate_path: "page:num"
twitter_username: "@astrofruzsi"
github_username: "jonathan-d-shaw"
linkedin_username: "fruzsina-julia-agocs"
# To render maths:
#markdown: kramdown
#kramdown:
#    math_engine: mathjax
include:
    - _static

# About/contact
author:
  name:              Jonathan D. Shaw
  url:               https://jonathan-d-shaw.github.io
  email:             jonathan.shaw@colorado.edu

# Custom vars
# version:             1.0.0
